name: Docker image CI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches:
    - main
    - master
    - default
    - develop
    tags:
    - release-*
  pull_request:
    branches:
    - main
    - master
    - default
    - develop
  workflow_dispatch:

jobs:
  docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps: 
    - name: Check out the repo
      uses: actions/checkout@v4.2.2
      
    - name: Check out the repo
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ github.repository }}-configs-dev
        path: 'helm-configs-dev'
        
    - name: Check out the repo
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ github.repository }}-configs-test
        path: 'helm-configs-test'
        
    - name: Check out the repo
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ github.repository }}-configs-prod
        path: 'helm-configs-prod'

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1.4.4
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

  helm_chart:
    - run: chmod 700 init_helm.sh
    
    - run: ./init_helm.sh ${{ env.BRANCH_NAME }}
    
    - name: Release Helm chart
      uses: flownative/action-helm-release@v2.0.1
      with:
        charts_folder: helm
        chart_name: ${{ env.IMAGE_NAME}}
        chart_version: ${{ env.BRANCH_NAME }}
        app_version: ${{ env.BRANCH_NAME }}
        registry_host: ${{ env.REGISTRY }}
        repository_path: ./
        repository_user: ${{ github.actor }}
        repository_password: ${{ secrets.GITHUB_TOKEN }}