name: Docker image CI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: 
    - main
    - master
    - default
    - develop
    tags:
    - release-*
  pull_request:
    branches: 
    - main
    - master
    - default
    - develop
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4.2.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1.4.4
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
    
    - name: Init helm
      run: chmod 700 ./init_helm.sh && ./init_helm.sh

    - name: Helm Publish Action
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: ${{ env.IMAGE_NAME}}
        repository: ${{ env.IMAGE_NAME}}
        tag: ${{ steps.meta.outputs.labels['org.opencontainers.image.version'] }}
        path: helm
        registry: ${{ env.REGISTRY }}
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'